version: '3'
services:
  ssh-web:
    build: .
    ports:
      - "880:80"
    volumes:
      - .:/ssh_blocker
  ssh-postgres:
    image: "postgres:10-alpine"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
